services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitoriamelo1/rodas:latest
    command: /bin/bash -c "uv run manage.py migrate --noinput"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rodas

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vitoriamelo1/rodas:latest
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - REDIS_URL=redis://redis:6379/1
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrator:
        condition: service_completed_successfully
    networks:
      - rodas

  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-rodas}
      POSTGRES_PASSWORD: ${DB_PASS:-rodas}
      POSTGRES_DB: ${DB_NAME:-rodas}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-rodas}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rodas

  redis:
    image: redis:8.2-alpine
    restart: unless-stopped
    networks:
      - rodas

networks:
  rodas:
    driver: bridge
